### ISSUE TITLE
[FEATURE] 자체개션 + 서비스 계층 테스트

### ISSUE THREAD

**Issue by skehdxhd96** [daedongbread/bread-map-backend-2#309]
- [ ] 좋아요 캐싱 / 이벤트 기반 변경 고려
- [ ] 서비스 계층 테스트
- [ ] 쿼리 최적화 작업
- [ ] feature/269 리뷰받았던거 반영 작업
       - domain parameter dto -> entity 변경

- [ ] 프로젝트 전체적으로 쿼리 튜닝 보기 

---

- [ ] 커뮤니티 상세 부분 이미지 가져오는 부분이 살짝 느림 
- [ ] 좋아요 부분 RDB말고 Redis로 처리할 필요 있어보임

**Comment by facewise** [comment]
Close stale issue
